server:
 port: 9004
spring:
 application:
  name: video-server
 rabbitmq:
    host: localhost
    port: 5672
    username: caohh
    password: caohh
eureka:
 client:
  service-url:
   defaultZone: http://localhost:9000/eureka/
foo: bar
