server:
 port: 9004
spring:
 application:
  name: video-server
 rabbitmq:
    host: 129.28.30.208
    port: 5672
    username: user
    password: pass
eureka:
 client:
  service-url:
   defaultZone: http://localhost:9000/eureka/
