server:
  port: 9002
spring:
  application:
    name: zuul-server
  rabbitmq:
    host: 129.28.30.208
    port: 5672
    username: user
    password: pass
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
 ignoreServices: '*'
 routes:
  sso-server: /sso/**
  video-server: /video/**
 sensitive-headers: 
ribbon:
 ReadTimeout: 5000
 SocketTimeout: 5000
