server:
  port: 9002
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
 routes:
  sso_server:
   path: /sso-server/**
   server-id: sso-server
   stripPrefix: true
 sensitive-headers: 
