server:
  port: 9002
spring:
  application:
    name: zuul-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
 ignoreServices: '*'
 routes:
  local:
   path: /actuator/**
   url: forward:/actuator
  sso-server: /sso/**
  video-server: /video/**
  web-server: /**
 sensitive-headers: 
ribbon:
 ReadTimeout: 5000
 SocketTimeout: 5000
