server:
  port: 9002
spring:
  application:
    name: zuul_server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
 routes:
  sso_server:
   path: /sso_server/**
   server-id: sso_server
 sensitive-headers: 
